version: '3.3'

services:
  android_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
    volumes:
      - ./postgres_folder:/var/lib/postgresql
  android_web:
    build:
      context: https://github.com/3kybika/android-serv.git
    restart: unless-stopped
    container_name: web
    ports:
      - 8081:8081
    depends_on:
      - android_postgres
