version: '3'
services:
  test_server:
    build:
      context: https://github.com/3kybika/android-serv.git
    restart: unless-stopped
    container_name: test_server
    ports:
      - 80:8081
      - 5432:5432