version: '3.3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
    ports:
    - 5432:5432
  web:
    build:
      context: https://github.com/3kybika/android-serv.git
    restart: unless-stopped
    container_name: web
    ports:
      - 8081:8081
    links:
      - postgres
   