CREATE TABLE IF NOT EXISTS  users (
  id SERIAL NOT NULL PRIMARY KEY,
  login VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL NOT NULL PRIMARY KEY,
  author_id INT NOT NULL,
  caption VARCHAR(255) NOT NULL,
  about VARCHAR(1024),
  checked BOOLEAN
);